# Enable the hardware console peripheral and logging pipelines
CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y

# Enable internal GDB debugging hooks
CONFIG_DEBUG=y

# Disable heavy compiler optimization so code maps 1:1 with source files
CONFIG_DEBUG_OPTIMIZATIONS=y

# Enable the Display subsystem
CONFIG_DISPLAY=y

# Enable the SDL (Window) Display Driver
CONFIG_SDL_DISPLAY=y

# Enable standard C++ library support (provides the 'new' and 'delete' operators)
CONFIG_CPP=y

# Give the RTOS a standard system heap size
CONFIG_HEAP_MEM_POOL_SIZE=16384

# Set custom Boot Banner to 'Vidya OS'
CONFIG_BOOT_BANNER=y
CONFIG_BOOT_BANNER_STRING="Booting Vidya OS"

# Enable reboot APIs
CONFIG_REBOOT=y

# Enable full C++ standard library support (using host compiler's STL on native_sim)
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP17=y

# Enable standard Zephyr Sensor Subsystem
CONFIG_SENSOR=y

# Enable Zephyr's portable console subsystem and getline utilities
CONFIG_CONSOLE_SUBSYS=y
CONFIG_CONSOLE_GETLINE=y