#!/bin/sh
case "$1" in
  start)
    printf "Starting VidyaOS Desktop Compositor... "
    # Redirect standard input/output to the virtual serial port
    /usr/bin/vidyaos-native < /dev/ttyS0 > /dev/ttyS0 2>&1 &
    echo "OK"
    ;;
  stop)
    printf "Stopping VidyaOS Desktop Compositor... "
    killall vidyaos-desktop
    echo "OK"
    ;;
  restart|reload)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac
exit 0
