[system]
compatible=VidyaOS x86_64
bootloader=grub
mountprefix=/mnt/system
statusfile=/var/status.rauc

[keyring]
path=/etc/rauc/ca.cert.pem

[slot.rootfs.0]
device=/dev/sda2
type=ext4
bootname=slot0

[slot.rootfs.1]
device=/dev/sda3
type=ext4
bootname=slot1
